### ISSUE TITLE
Dark Mode to Light Mode Switch not working in Mobile View

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#382]
![darkmode_mobile](https://user-images.githubusercontent.com/46641503/103205020-9ace7400-491e-11eb-9847-32414170c597.jpg)

Additionally, the switch should work on click anywhere in that region rather than the concentric circle only

**Comment by AdityaTeltia** [comment]
I can try working on this assign me this issue !

**Comment by smaranjitghose** [comment]
> I can try working on this assign me this issue !

You are in which program?

**Comment by AdityaTeltia** [comment]
I am swoc program

**Comment by ayushrastogi689** [comment]
I would like to work on this issue.
I am a participant of SWoC 2021.

**Comment by aum-singhal** [comment]
I can also contribute on this program.
I am a participant of SWoC 2021.

**Comment by AdityaTeltia** [comment]
I will make the related to this issue after 4Jan for SWOC program if np? @smaranjitghose

**Comment by smaranjitghose** [comment]
> I will make the PR related to this issue after 4Jan for SWOC program if np? @smaranjitghose

I would suggest making the PR earlier if possible, so that we can give feedback and you don't need to wait till 4th for making the changes. That way you get a headstart

**Comment by AdityaTeltia** [comment]
Ok ! Will make the pr as soon as the issue is resolved .

**Comment by AdityaTeltia** [comment]
I haven't changed anything in the codebase but issue seemed resolved the toggle is working in mobile too.
![working](https://user-images.githubusercontent.com/67232537/103403483-43c2dc00-4b76-11eb-87b4-e5fe58cc6d38.JPG)

**Comment by dipanshparmar** [comment]
@anushbhatia and @smaranjitghose this is not an issue actually. This works fine if you reload the page after switching to a smaller view:

https://user-images.githubusercontent.com/49204837/103421412-32072600-4bc2-11eb-86d2-91863e8629a3.mp4


The issue here is that there are two different navbars for desktop view and mobile view.
**Desktop view**
![image](https://user-images.githubusercontent.com/49204837/103420870-78a75100-4bbf-11eb-8747-205be02bb88c.png)

**Mobile view**
![image](https://user-images.githubusercontent.com/49204837/103420887-85c44000-4bbf-11eb-91c7-541e3f4c9515.png)

and we are selecting them according to the screen sizes:
![image](https://user-images.githubusercontent.com/49204837/103420911-a5f3ff00-4bbf-11eb-8a3b-ecedd8f4d669.png)

That's the reason why the navbar doesn't work when we switch to the mobile view from the desktop view because the desktop's navbar is already selected there. So in order to make the mobile's navbar work we need to reload the page so that it selects the mobile's navbar. When the user opens the website in the mobile view then the mobile's navbar will be selected there by default, and it will work fine. So I don't think there is anything to worry about.
