### ISSUE TITLE
Mobile Nav Bar Splash Animation

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#648]
[Reference](https://www.hellomonday.com/)

- **We are looking for just the inverse color splash as shown in the reference above**
- The Nav Bar orientation should not be changed (our effect should take place from top to bottom rather than right to left as seen in the above reference)
- The Hamburger Animation should not be changed
- The Nav Bar Text should not be changed

In case you are confused the splash animation should be after the pre-loader

**Comment by AKC068** [comment]
Hey!
I have gone through the reference link and I also liked that Nav Bar Splash animation personally. I would like to work on this and I can send you PR for this till 12th of June.
@smaranjitghose can you assign this to me ?

**Comment by AKC068** [comment]
![image](https://user-images.githubusercontent.com/59188454/121388747-5e8d4e00-c969-11eb-9168-2518e88e0afe.png) ![image](https://user-images.githubusercontent.com/59188454/121388860-749b0e80-c969-11eb-97cf-beb8f20b5fc4.png)

I have a doubt that you have mentioned '**We are looking for just the inverse color splash as shown in the reference above**', which means that when nav bar expands bg color should be black but in that case the bg colour is white and currently the site which we can see having bg color also greyish white so in that case even if the splash is being implemented it will not be visible due to color combination.
@smaranjitghose please let me know if I've got it wrong

**Comment by smaranjitghose** [comment]
@AKC068  I agree. And currently, both @anushbhatia and I are brainstorming to improve the overall UI including the color scheme. Therefore I am closing this issue

**Comment by AKC068** [comment]
Okey @smaranjitghose, so if  get any idea can I open a issue regarding this?

**Comment by anushbhatia** [comment]
Yeas sure.
