### ISSUE TITLE
Navbar UI Enhancement  ( Hover Transition)

### ISSUE THREAD

**Issue by Kabirdutt** [smaranjitghose/awesome-portfolio-websites#677]
The header section has buttons like home, experience, etc. Hover effect along with shadows  could be added to the item and an onclick effect could be added as well

**Comment by siddhi-244** [comment]
I am LGM SOC participant shall I try this?

**Comment by siddhi-244** [comment]
Plzz assign it to me!

**Comment by Devansh2000Shaw** [comment]
I want to contribute on this issue under LGM SOC 21. Thank you.

**Comment by vimalprogrammer** [comment]
I would like to contribute to this issue, please assign me.

**Comment by anushbhatia** [comment]
Sure how would you do so just give a brief example if possible?

**Comment by harshit-dugar** [comment]
I am also a participant of LGM SOC can I also contribute

**Comment by aditya687** [comment]
I want to improve the header section and  can  also contribute

**Comment by sejalvasan** [comment]
Can you please assign this issue to me?

**Comment by smaranjitghose** [comment]
@anushbhatia Let's give @Kabirdutt 3 days and see the improvements over a PR

**Comment by AnjaniSriya** [comment]
I am a memeber of LGM SOC, 
I would like to contribute, please allow me

**Comment by dhruv-varshney** [comment]
May i contribute and resolve this issue.Please assign me to resolve this issue.

**Comment by dhruv-varshney** [comment]
May you label the level also. That will be helpful .

**Comment by smaranjitghose** [comment]
@dhruv-varshney @AnjaniSriya @sandeep9889 

Please understand that whenever a participant raises an issue, by default it would be assigned to that participant only and not anyone else due to obvious reasons. Hence blindly commenting "I would like to contribute" is not an ideal practice. You are free to do this whenever a project maintainer (in the case of this project, @anushbhatia or I ) raises an issue(s).

@dhruv-varshney Please refrain from putting multiple single-line comments. It unnecessarily makes the issue thread long. And as far as labels go, all the maintainers/mentors are aware of the evaluation criterion and you need not help us with that.

**Comment by dhruv-varshney** [comment]
ok, I will make sure that will not happen again in the future.

**Comment by 2024-SANDHYA** [comment]
I want to contribute for the same under LGM SOC'21

**Comment by pravleen17** [comment]
I am LGM-SOC21 contributor. I would like to work on this issue. Please assign it to me.

**Comment by phreakyphoenix** [comment]
@pravleen17 @2024-Sandhya please read the previous messages in this thread, in particular https://github.com/smaranjitghose/awesome-portfolio-websites/issues/677#issuecomment-859962119

Please read the contribution guide to avoid a barrage of needless messages. Happy contributing.
