### ISSUE TITLE
Smooth transition on buttons hover

### ISSUE THREAD

**Issue by supzi-del** [smaranjitghose/awesome-portfolio-websites#686]
When the buttons in nav bar are hovered, there is no transition. To make it smooth, I would like to add this. Please assign this to me

**Comment by nekkantimadhu** [comment]
I would like to contribute on this issue under LGM SOC 21, Could you please assign this issue to me?

**Comment by smaranjitghose** [comment]
Assigned to @supzi-del.

@nekkantimadhu Please understand that whenever a participant raises an issue, by default it would be assigned to that participant only and not anyone else due to obvious reasons. Hence blindly commenting "I would like to contribute" is not an ideal practice. You are free to do this whenever a project maintainer (in the case of this project, @anushbhatia or I ) raise an issue(s).

**Comment by 0xCipher-max** [comment]
I can make it more attractive if you want

**Comment by supzi-del** [comment]
@0xCipher-max If you want to add more features, please open your own issue and get assigned.

**Comment by smaranjitghose** [comment]
@0xCipher-max Please read my comment above or the guidelines provided in the slack workspace
