### ISSUE TITLE
Parallax Depth Cards for Project Page

### ISSUE THREAD

**Issue by smaranjitghose** [smaranjitghose/awesome-portfolio-websites#743]
[Reference](https://codepen.io/andymerskin/pen/XNMWvQ)

## Requirements (w.r.t to the above reference):

- Make the cards square
- Increase the size of the cards such that each row in the web view for a 15.6" screen has three cards.
- Adjust the size of text (title of the card) such that  30 letters can be fit in a responsive manner. Multi-line titles should be possible
- On Hover, the title should not be displaced up instead the github and web icon (already present on the current cards on the website) should appear on the bottom right.

**Comment by AKC068** [comment]
@smaranjitghose can you please assign me also this issue as my update is ready and I only have to make a PR.
As changes requested by @anushbhatia

**Comment by AKC068** [comment]
@smaranjitghose sir can you let me know that I got it right or wrong that in 4th point you are telling that without shifting the heading text on hover there should be preview and github icon on right ?
If it is like that then if letters are shifted on left and icons come there then it will look congested because everything will be in single line.

I'm making a PR and please review that and let me know that it is to be done or not....

**Comment by aliya-rahmani** [comment]
@AKC068 updates?

**Comment by AKC068** [comment]
I'm very sorry @aliya-rahmani I'm getting late but yes it is in progress and within three days I'll make a PR for this issue...

Because previously the changes which I had made was not according to the reference provided.
Sorry for inconvenience.

**Comment by aliya-rahmani** [comment]
Alright, then three days is the deadline for you.
