### ISSUE TITLE
Update Image Embeddings in the Readme with alt text for slower connections

### ISSUE THREAD

**Issue by bukolastella** [smaranjitghose/awesome-portfolio-websites#946]
Adding a link that leads to the contribution guidelines because in case of slow network the image fails to load
![awe](https://user-images.githubusercontent.com/53631117/125838682-c73209fa-539d-43cb-ae76-06bdcbdf6fff.PNG)

please assign me to this task

**Comment by smaranjitghose** [comment]
Hey @bukolastella 

Thanks for bringing this to our notice and welcome to our project.

After close inspection, we concluded that this problem is arising due to the network connection issues at times and it is independent of the readme's markdown code written for the repo where we have the images and as well as the link for the contributing.md guidelines.

Do let us know if there are any queries, we would be happy to help out.

**Comment by bukolastella** [comment]
Alright, I was thinking adding a link inline will be good, so in the case of screenshot above you can click on it instead of waiting for the image to load

**Comment by anushbhatia** [comment]
One suggestion you could do is add alt="Mentor Name Here" and use and  `<img>` tag instead of Github's default image call.
@smaranjitghose what say?

**Comment by smaranjitghose** [comment]
@anushbhatia . That makes sense.

@bukolastella Would you like to give a PR for this?

**Comment by bukolastella** [comment]
@smaranjitghose  yes,sure
